#!/usr/bin/env bash
set -eu

SOLANA_CONFIG_DIR=/mnt/ledger

mkdir -p $SOLANA_CONFIG_DIR
NDEBUG=1 ./multinode-demo/setup-mainnet.sh
cargo run --release --bin solana-ledger-tool -- -l /mnt/ledger/config/bootstrap-validator/ create-snapshot 0
