#!/usr/bin/env bash
set -eu

SOLANA_CONFIG_DIR=/mnt/ledger

mkdir -p $SOLANA_CONFIG_DIR
NDEBUG=1 ./multinode-demo/setup-mainnet.sh
mv ./config/* $SOLANA_CONFIG_DIR/
cargo run --release --bin solana-ledger-tool -- -l $SOLANA_CONFIG_DIR/bootstrap-validator/ create-snapshot 0
